version: '3.8'

services:
  # Backend service
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: typingrace-server
    environment:
      - NODE_ENV=production
    env_file:
      - .env.docker
    volumes:
      - ./server:/app/server
    restart: unless-stopped

  # Frontend service
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: typingrace-client
    environment:
      - NODE_ENV=production
      - VITE_SERVER_URL=${SERVER_URL:-http://localhost:3000}
    env_file:
      - .env.docker
    volumes:
      - build-output:/app/dist
    depends_on:
      - server
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    container_name: typingrace-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - build-output:/usr/share/nginx/html
    depends_on:
      - client
      - server
    restart: unless-stopped

volumes:
  build-output: