FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy only the client files
COPY tsconfig*.json ./
COPY vite.config.ts ./
COPY index.html ./
COPY src ./src


# here we export the port
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
